CREATE TABLE IF NOT EXISTS users
(
  id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name   varchar(255) NOT NULL,
  email  varchar(64) NOT NULL,
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  description   TEXT,
  requestor_id  BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items
(
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name        varchar(255) NOT NULL,
  description TEXT,
  available   boolean,
  owner_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  request_id  BIGINT REFERENCES requests(id) ON DELETE CASCADE -- NOT NULL?
);

CREATE TABLE IF NOT EXISTS bookings
(
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  start_date  TIMESTAMP WITHOUT TIME ZONE,
  end_date    TIMESTAMP WITHOUT TIME ZONE,
  item_id     BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  booker_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status      varchar(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
  id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  text       TEXT,
  item_id    BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  author_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created    TIMESTAMP WITHOUT TIME ZONE
);


